info: 'Check whether Error 4108 is reported when enable_sql_audit is set to True.'
task:
  - version: "[4.0.0.0,*]"
    steps:
    - type: sql
      sql: 'select count(0) from oceanbase.GV$OB_PARAMETERS where NAME="enable_sql_audit" and VALUE<>"True" ;'
      result:
        set_value: sql_audit
        # report_type: warning
        verify: "[ '0' ==  ${sql_audit} ]"
        err_msg: 'Unable to proceed because enable_sql_audit is set to False'
    - type: sql
      sql: 'select count(0) from oceanbase.GV$OB_SQL_AUDIT where RET_CODE ="-4108";'
      result:
        set_value: err_4108
        verify_type: equal
        verify: 0
        err_msg: 'number of sql_error_4108 is #{err_4108}. maybe the disk is damaged.'
    - type: ssh
      ssh: "grep \"checksum error\"  #{remote_home_path}/log/observer.log | awk '{print $1}'"
      result:
        set_value: checksum_error_log
        verify: '[ -z "$checksum_error_log" ]'
        err_msg: "node #{remote_ip} has checksum error log in #{remote_home_path}/log/observer.log . maybe the disk is damaged. please check it."



